In [7]:
import numpy as np

def generateMatrix(vector, n, increasing=False):
    
    if not increasing:
        op = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
    elif increasing:
        op = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    
    return op


inputvector = np.array([1,2,3,4,5])
col = 5
opdec = generateMatrix(inputvector,col,False)
opaec = generateMatrix(inputvector,col,True)

print(opdec)
print("-----------------------------")
print(opaec)


print ("using Vander")

vanoutput = np.vander(inputvector, col,True)
vanoutput1 = np.vander(inputvector, col,False)

print(vanoutput)
print("------------------------------------")
print(vanoutput1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
-----------------------------
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
using Vander
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
------------------------------------
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [15]:
numbers = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size = 3

i = 0
movingAverages = []
while i < len(numbers) - window_size + 1:
    window = numbers[i : i + window_size]

    windowAverage = sum(window) / window_size
    movingAverages.append(windowAverage)
    i += 1

print(movingAverages)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
